name: Build and Attest Artifact

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write        # Required for Sigstore signing
  contents: read         # To access repository contents
  attestations: write    # To upload attestations

jobs:
  build-and-attest:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Example: Build an output file (replace with your build command)
      - name: Build the artifact
        run: |
          # Example: Compile a C program or similar
          echo "Building a sample binary..."
          gcc -o my-app main.c  # Replace with your build command (e.g., mvn package, npm run build)
          mkdir -p dist
          mv my-app dist/my-app
        # Ensure the output file is created in a known path (here: dist/my-app)

      # Generate attestation for the output file
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'dist/my-app'  # Path to the output file
          # Optional: subject-digest: 'sha256:<hash>' if you precompute the digest

      # Optional: Upload the artifact for download
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app
          path: 'dist/my-app'